### ISSUE TITLE
spectrwm crops and does not display entirely the action bar output

### ISSUE THREAD

**Issue by doums** [conformal/spectrwm#307]
Hi!

I noticed a bug, spectrwm crops and does not display the entire output of the action bar. Playing with alignment, padding, bar section and even specifying a limit length does not help.
I isolated a simple reproduction so that you can reproduce it easily.

First, the spectrwm relevant config:
```
...
# Bar Settings
bar_enabled = 1
bar_border_width = 5
bar_enabled_ws[2] = 0
bar_border[1] = rgb:37/40/29
bar_border_unfocus[1] = rgb:37/40/29
bar_color[1] = rgb:37/40/29
bar_color_selected[1] = rgb:37/40/29 bar_font_color[1] = rgb:f2/f2/f0,rgb:ed/51/35,rgb:9b/a6/72
bar_font_color_selected = rgb:f2/f2/f0
bar_font = JetBrains Mono:pixelsize=22:antialias=true,Material Design Icons Desktop:pixelsize=22:antialias=true
bar_action = /path/to/bar_test.sh
bar_action_expand = 1
bar_justify = left
bar_format = +R:+I +S <+D> +A
# workspace_indicator = listcurrent,listactive,markcurrent,printnames
bar_at_bottom = 1
clock_enabled = 0
```
You can download the fonts here:
[JetBrains Mono](https://www.jetbrains.com/lp/mono/)
[Material Design Icons Desktop](https://github.com/Templarian/MaterialDesign-Font/blob/master/MaterialDesignIconsDesktop.ttf)

Finally a dummy script
(copy/paste it as it is, it contains several unicode characters that you can see with the material design font)
```
#!/bin/sh

echo " 15% +@fg=0;+@fn=1;󰻠+@fn=0;+@fg=0;   48° +@fg=0;+@fn=1;󱃃+@fn=0;+@fg=0;   50% +@fn=1;󰃟+@fn=0;   35% +@fg=0;+@fn=1;󰍬+@fn=0;+@fg=0;   33% +@fg=0;+@fn=1;󰖀+@fn=0;+@fg=0;   70% +@fg=0;+@fn=1;󰢞+@fn=0;+@fg=0;   Sat. 25 April 2020, 1h49"
```
Now if you do the test, you will see that " 1h49" (at then end of the output) is not displayed in the bar.

There is no error log concerning the bar in the log file (`spectrwm &> spectrwm.log`).

**Comment by LordReg** [comment]
The bar currently has a hard limit for handling bar_format + bar_action.  Perhaps this could be turned into an option or made dynamic in the future.  For now, a workaround would be to manually increase SWM_BAR_MAX in spectrwm.c:
```#define SWM_BAR_MAX             (256)```

**Comment by doums** [comment]
Hi! And thank for the quick response !

Ok, I suppose that all the individual characters in markup sequences like `+@fn=n;` are also counted in the total length? (Which explains that my example is cut when the final length of the displayed characters is not greater than 256).

> Perhaps this could be turned into an option

In a first time, that would be great ! I confirm.

**Comment by doums** [comment]
Hi, so any news on this ? I mean turn this define into a configurable option seems not be very complicated, I think (for someone which knows the code).

**Comment by LordReg** [comment]
It turns out the buffer sizes were not big enough to fit the current limits of bar_action output + bar_format.  I committed a fix for the inconsistency.

**Comment by doums** [comment]
Ok nice, thanks!

I don't know if you are the maintainer of the archlinux package, but if it's the case, can you please update it as well ?

**Comment by doums** [comment]
Hi,

I just tried again with spectrwm built from sources (updated from master). And the problem is still there.
For example if a bar script output something like:
```
" 0.9/16.5Go+@fg=0;+@fn=1;󰍛+@fn=0;+@fg=0;    3% +@fg=0;+@fn=1;󰻠+@fn=0;+@fg=0;   36° +@f    g=0;+@fn=1;󱃃+@fn=0;+@fg=0;   10% +@fn=1;󰃟+@fn=0;   65% +@fg=0;+@fn=1;󰕾+@fn=0;+@fg=0;  Live +    @fn=1;󰤥+@fn=0;  70% +@fg=0;+@fn=1;󰂀+@fn=0;+@fg=0;    Thu. 28 May 2020, 2h45
```
Instead of 
>  0.9/16.5Go󰍛    3% 󰻠   36° 󱃃   10% 󰃟   65% 󰕾  Live 󰤥  70% 󰂀    Thu. 28 May 2020, 2h45
>  0.9/16.5Go󰍛    3% 󰻠   36° 󱃃   10% 󰃟   65% 󰕾  Live 󰤥  70% 󰂀    Thu

**Comment by LordReg** [comment]
Increased the limits.  Shouldn't be an issue now.
